Improve get top moves
py-stockfish/stockfish pull request #16
Opened 2023-04-07 22:01 UTC by knutole

This PR combines and replaces https://github.com/py-stockfish/stockfish/pull/15 and https://github.com/py-stockfish/stockfish/pull/14, with major refactor of `get_top_moves()` function. (It was much easier to combine the PR's, for obvious reasons.)

Also added other points discussed in above PRs:
- Turn perspective or White's perspective. Option included, turn-based perspective as default.
- Cleanup of logic in `get_top_moves()`.

2023-04-08 22:53 UTC, kieferro commented
Wow, that's quite a PR. First of all, a big thank you for the work and the interest that you put in this project!
I am currently not able to test and review your code, but it looks like you're still at work anyway. So just ping us or request if you need a review.

2023-04-08 23:03 UTC, knutole commented
Thank you 🙏 This PR is ready for review 👌

2023-04-10 08:21 UTC, knutole commented
It's not possible for me to request review on this PR, by the way, not sure if there's a Github setting for that. @kieferro @johndoknjas

2023-04-14 23:59 UTC, kieferro requested changes
Okay, I am back and I looked at the changes. It looks very good overall!
We should, as you also wrote in your comment, implement the use of `turn_perspective` more consistently, but that's probably beyond the scope of this PR. This is definitely a good first step and we'll continue it from there.

2023-04-14 23:59 UTC, kieferro commented on stockfish/models.py
> +        # use Stockfish' values, otherwise invert values.
```suggestion
        # use Stockfish's values, otherwise invert values.
```

2023-04-14 23:59 UTC, kieferro commented on stockfish/models.py
> +    def _pick(self, line: list = [], value: str = "", index: int = 1) -> str:
```suggestion
    def _pick(self, line: list, value: str = "", index: int = 1) -> str:
```
Does it make sense to call the function without this parameter?

2023-04-15 00:02 UTC, kieferro commented
> It's not possible for me to request review on this PR, by the way, not sure if there's a Github setting for that. @kieferro @johndoknjas

Ah okay, I see. But [it seems that nothing can be done](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) about that as long as you don't have write-access. But feel free to just use the draft PR feature to indicate when the PR is ready for review.

2023-04-16 00:16 UTC, knutole commented on stockfish/models.py
> +            depth: Depth as integer higher than 1
```suggestion
depth: Depth as integer 1 or higher
```

2023-04-17 10:51 UTC, kieferro approved these changes

2023-04-17 10:51 UTC, kieferro commented on README.md
> +Optional parameter `num_nodes` specifies the number of nodes to search. If num_nodes is 0, then the engine will search until it configured depth is reached.
```suggestion
Optional parameter `num_nodes` specifies the number of nodes to search. If num_nodes is 0, then the engine will search until it's configured depth is reached.
```

2023-04-17 10:51 UTC, kieferro commented on README.md
> +### Set perspective of the evaluation
Maybe we should specify here that so far this setting only affects `get_top_moves`.

2023-04-17 10:51 UTC, kieferro commented on tests/stockfish/test_models.py
> +    def test_set_num_nodes_raises_type_error(self, stockfish):
Here I would also prefer to use `@pytest.mark.parametrize`. I must have overlooked this test last time.

2023-04-20 05:08 UTC, johndoknjas approved these changes
The changes look good, and the tests pass for me - nice job! Thanks for your contribution.

2023-04-20 05:11 UTC, merged

2023-04-20 05:12 UTC, johndoknjas commented
Looks like we're all satisfied with the PR, so I've merged it into master.

2023-04-20 05:16 UTC, knutole commented
Great, thanks 🙏👍

2023-04-20 19:10 UTC, kieferro commented
> Looks like we're all satisfied with the PR, so I've merged it into master.

Thanks :+1:

Congratulations @knutole. Could you close your two PRs in the old repo (https://github.com/zhelyabuzhsky/stockfish/pull/115, https://github.com/zhelyabuzhsky/stockfish/pull/116)? This would give us a better overview.